package Exception;

public class ExceptionSample1 {
	public static void main(String[] args) {
		int[] a = new int[3];
		System.out.println("値を代入します。");
		a[3] = 30;
		System.out.println("処理を終了します");
	}
}
